latchbio/latch

docs/source/basics/local_development.md
docs/source/index.md
setup.py

the ability to execute workflows as python functions with valid python literals
```
@small_task
def foo(a: LatchFile) -> LatchFile:
with open(a) as f:
print(f.read())
b = Path("new.txt").resolve()
with open(b, "w") as f:
f.write("somenewtext")
return LatchFile(str(b), "latch:///remote_location/a.txt")
@workflow
def bar(a: LatchFile) -> LatchFile:
"""
...
"""
return foo(a=a)
if __name__ == "__main__":
bar(a=LatchFile("/root/reads.fa"))
```

local execution

---

docs/source/basics/local_development.md
docs/source/subcommands.md
latch/cli/main.py
latch/services/__init__.py
latch/services/local_execute.py
latch/services/register/__init__.py
latch/services/register/register.py
tests/test_register.py

Execute a workflow within the latest registered container. Run from the
outside the pkg root, eg. `latch local-execute myworkflow` where
`myworkflow` is the directory containing your workflow package.
This is the same as running:
$ python3 wf/__init__.py
Assuming this file contains a snippet conducive to local execution such as:
if __name__ == "__main___":
my_workflow(a="foo", reads=LatchFile("/Users/Von/Neuman/machine.txt")

local execution in docker

---

README.md

These are both well-documented and relatively simple workflows that can be a nice launching point for others looking to contribute to the SDK. Furthermore, they cover relatively common analyses conducted by bioinformaticians: inferring the evolutionary history of sequences and estimating codon optimization.

updated README with two examples of latch workflows

---

latch/__init__.py
latch/functions/operators.py

feat: operators

---

latch/__init__.py
latch/resources/tasks.py

feat: custom resource specs

---

latch_cli/click_utils.py
latch_cli/main.py

Improve CLI helptext

---

latch_cli/main.py
latch_cli/services/ls.py
latch_cli/utils.py

Restyled `ls` to this:
Inspired by [`exa`'s](https://the.exa.website/) color scheme:

restyle ls to work like exa

---

latch_cli/config/latch.py
latch_cli/main.py
latch_cli/services/test_data/ls.py
latch_cli/services/test_data/remove.py
latch_cli/services/test_data/upload.py
latch_cli/services/test_data/utils.py
setup.py

```
Commands:
ls      List test data objects.
remove  Remove test data object.
upload  Upload test data object.
```

data upload cmds

---

docs/source/basics/customizing_interface.md
docs/source/basics/remote_execution.md
docs/source/basics/uploading_test_data.md
docs/source/basics/what_is_a_workflow.md
docs/source/index.md
docs/source/subcommands.md
latch_cli/services/init.py

- dockerfile commands are reordered to build faster in general
- launchplan exists
- metadata is python object not docstring yaml

small improvements to boilerplate

---

docs/source/examples/docker_recipes.md

@hannahle suggested I add R installation example to docs for others to use.

add R installation to dockerfile_recipes.md 

---

latch_cli/crash_reporter.py
latch_cli/main.py
latch_cli/services/register/__init__.py
latch_cli/services/register/register.py

Added function to save docker build logs to help debug. 
Logs are automatically stored under `{pkg_root}/logs/docker-build-logs.txt`.

add function to save docker build logs

---

latch/resources/reference_workflow.py
latch/verified/__init__.py
latch/verified/deseq2.py
latch/verified/pathway.py
latch/verified/rnaseq.py

curated wf references for verified wfs

---

latch_cli/auth/oauth2.py
latch_cli/main.py
latch_cli/services/login.py

Signed-off-by: maximsmol <maximsmol@gmail.com>

add custom connections to login

---

latch_cli/constants.py
latch_cli/crash_reporter.py
latch_cli/main.py
latch_cli/services/register/models.py
latch_cli/utils.py
setup.py

add check to version

---

latch_cli/services/get_executions.py

fix get executions to work with sub workflows

---

latch_cli/services/cp.py
setup.py

cp: fixes for part ordering + empty file uploads

---

latch/types/__init__.py
latch/types/metadata.py

add forks+flows to metadata obj

---

CHANGELOG.md
latch/resources/workflow.py

check params in metadata vs wf

---

CHANGELOG.md
latch_cli/services/get_params.py
setup.py

escape python keywords in enum variants

---

CHANGELOG.md
latch_cli/main.py
latch_cli/services/preview.py

fix preview to take in a package root and use idl instead of hacks

---

CHANGELOG.md
latch_cli/config/latch.py
latch_cli/exceptions/traceback.py
latch_cli/services/local_dev.py

throw error when user tries to develop an un-registered wf + fix error reporter

---

CHANGELOG.md
latch/types/metadata.py
setup.py

Signed-off-by: maximsmol <maximsmol@gmail.com>

allow disabling standard bulk execution

---

CHANGELOG.md
latch_cli/services/cp.py
setup.py

Signed-off-by: maximsmol <maximsmol@gmail.com>

fix latch cp content type

---

latch_cli/centromere/utils.py

[offending line](https://github.com/theorchard/openpyxl/blob/master/openpyxl/xml/__init__.py#L11)

make fake import object comparable

---

latch/resources/launch_plan.py
latch/resources/map_tasks.py
latch/resources/tasks.py
latch/resources/workflow.py

fix typing for tasks/workflows/map_tasks

---

latch_cli/centromere/utils.py

Revert "make fake import object comparable"

---

CHANGELOG.md
latch/registry/table.py
latch/types/file.py
latch_cli/main.py
latch_cli/services/cp/download.py
latch_cli/services/cp/ldata_utils.py
latch_cli/services/cp/main.py
latch_cli/services/cp/path_utils.py
latch_cli/services/cp/remote_copy.py
latch_cli/services/cp/upload.py
latch_cli/services/move.py
setup.py

remote->remote latch cp and latch mv

---

CHANGELOG.md
latch_cli/centromere/ctx.py
latch_cli/centromere/utils.py
latch_cli/main.py
latch_cli/services/register/register.py
setup.py

gate new register behind flag

---

CHANGELOG.md
latch/types/directory.py
latch/types/file.py
setup.py

normalize paths to respect user workspace setting

---

latch/types/directory.py
latch/types/file.py
latch_cli/snakemake/serialize.py
latch_cli/snakemake/workflow.py

modify sm jit workflow to only touch files and not download them

---

CHANGELOG.md
latch_cli/snakemake/workflow.py
setup.py

right now snakemake workflows only work for the user who registered them

make snakemake wf work for any subscribed user

---

latch_cli/menus.py
latch_cli/services/workspace.py

- add a `> ` indicator for selection
- mark the current workspace
- don't clear screen
- change color

tiny enhancements for latch workspace

---

latch_cli/snakemake/workflow.py

Previously we were using the param name instead of the file name to find the upstream node for a given target. The issue with this is that the target job's input param name is not always guaranteed to have the same name as the output param of the upsteam node. 
Therefore, we should compare the filenames to find the upstream node of a particular file and then use the param name to bind the outputs.

use target job file name instead of param name to resolve upstream nodes

---

docs/source/index.md
docs/source/snakemake/environments.md
latch/types/metadata.py
latch_cli/services/register/register.py
latch_cli/snakemake/single_task_snakemake.py
latch_cli/snakemake/workflow.py

1. Add config for enabling/disabling conda and containers
2. Some formatting changes b/c I upgraded my local version of black 
3. Added docstrings for snakemake metadata fields
4. Docs

Add environment config in latch_metadata

---

latch/types/metadata.py
latch_cli/extras/common/utils.py
latch_cli/extras/nextflow/build.py
latch_cli/extras/nextflow/tasks/operator.py
latch_cli/extras/nextflow/tasks/process.py
latch_cli/services/register/utils.py

```
@dataclass
class Sample:
sample: str
breakend_file: LatchFile
is_control: bool
def construct_samplesheet(samples: typing.List[Sample]) -> Path:
samplesheet = Path("samplesheet.csv")
with open(samplesheet, "w+") as f:
fieldnames = ["sample", "breakend_file", "is_control"]
writer = csv.DictWriter(f, fieldnames=fieldnames)
writer.writeheader()
for sample in samples:
writer.writerow(
{
"sample": sample.sample,
"breakend_file": sample.breakend_file,
"is_control": sample.is_control,
}
)
return samplesheet
generated_parameters = {
"samplesheet": NextflowParameter(
display_name="Samplesheet",
samplesheet=True,
samplesheet_constructor=construct_samplesheet,
type=typing.List[Sample],
),
...
```

samplesheet support for nextflow

---

latch/resources/tasks.py
latch/types/metadata.py
latch_cli/main.py
latch_cli/nextflow/config.py
latch_cli/nextflow/dependencies.py
latch_cli/nextflow/types.py
latch_cli/nextflow/workflow.py
latch_cli/services/register/register.py
latch_cli/snakemake/config/utils.py
setup.py

about page + 
nextflow versioning + 
add import latch_metadata in entrypoint file +
add --process-executor flag

Misc Nextflow Changes

---

CHANGELOG.md
latch/types/metadata.py
setup.py

add ability to restrict samplesheet component to only read from certain tables

---

CHANGELOG.md
latch/ldata/_transfer/upload.py
latch_cli/constants.py
latch_cli/main.py
latch_cli/services/cp/main.py
latch_cli/tinyrequests.py
setup.py

- lower default chunk size to 64mib
- allow chunk size to be configurable via `--chunk-size-mib`
- add connection reuse to tinyrequests

various cp enhancements

---

CHANGELOG.md
latch/ldata/_transfer/download.py
latch/ldata/_transfer/upload.py
latch/ldata/_transfer/utils.py
latch_cli/tinyrequests.py
setup.py

this gives us connection reuse and retries for free
also includes 429 rate limits

switch to session

---

latch_cli/snakemake/serialize.py

Per Slack discussion - providing additional information here would be super helpful when troubleshooting errors that arise during the JIT registration

feat: Report the underlying error when a Snakefile cannot be serialized

---

pyproject.toml
src/latch/types/plots.py
uv.lock

```
const artifactJson = z.object({
bindings: z.object({
plotTemplates: z.array(
z.object({
id: z.string(),
widgetValues: z.optional(z.record(z.any())),
}),
),
}),
});
```
for reference

dataclass for artifact json

---

CHANGELOG.md
pyproject.toml
src/latch/resources/launch_plan.py

Revert "Aidan/add description to lp"

---

CHANGELOG.md
pyproject.toml
src/latch/resources/workflow.py
src/latch/types/metadata.py

Signed-off-by: Ayush Kamat <ayush@latch.bio>Signed-off-by: Ayush Kamat <ayush@latch.bio>

add about md info on every register

---

CHANGELOG.md
pyproject.toml
src/latch_cli/main.py
src/latch_cli/services/k8s/develop.py
src/latch_cli/services/register/register.py
src/latch_cli/services/register/staging.py

register --staging
