latchbio/latch

setup.py

bumps flaighkit to `v0.4.0` which removes `pyarrow` from the dependency list. this eliminates a build bug on m1 mac.

fix: bump flaightkit

---

.github/workflows/test.yaml
latch/cli/main.py

Right now, you get a cryptic error message when you register a workflow with an illegal name (see #60). I've added a check when initializing a workflow that prints a clear error message if you attempt to initialize a workflow with an illegal name (I've defined an illegal name as anything with capital letters or that ends in _ or -, though this isn't exhaustive). I haven't tested this, since the repository doesn't give build instructions, but it's only three if statements.

Added error message when initializing illegal workflow name

---

docs/source/basics/conditional_and_map_tasks.md
latch/resources/conditional.py

Fixes example in the conditionals section of the documentation. It had missing arguments and mentioned variables that don't exist before.
- Closes #84

docs: Fix conditionals example in documentation

---

setup.py

Updates lytekit version to fix:
* out of order field validation in records
* `Union[R_1, R_2]`, where `R_1 | R_2` are records, transforming to incorrect python value at runtime

pin lytekit + lytekitplugin

---

latch/types/directory.py
latch/types/file.py

* Typically occurs when LatchFiles and LatchDirs passed as input to
a task are also included in the output (this is useful, i.e. when
preparing inputs for a map task).

fix: stop unneeded download and reupload on files

---

latch_cli/services/mkdir.py

The `mkdir` endpoint will report success/failure without the need to double-check the directory got created
This cuts out a round-trip + removes the need to keep `/verify` updated as we add new features. `/verify` could also be rewritten to properly use stored procedures but since it's kind of useless anyway I think it's better to just phase it out and eventually remove it entirely

Do not unnecessarily double-check directory creation

---

latch/types/directory.py
latch/types/file.py

- Removes 'remote_path=' that is added as placeholder
- Closes #103

refactor: Make LatchFile/Dir get-params friendlier

---

latch/types/directory.py
latch/types/file.py

```
@dataclass
@dataclass_json
class Foo():
a: LatchFile
one = Foo(a=LatchFile("/tmp/sample.txt").to_json()
two = Foo(a=LatchFile=(Path("/tmp/sample.txt")).to_json()
```
`one` and `two` have different serialized representations that throw off the typetransformer. we consider these to be the same values

consistent json repr

---

latch_cli/services/register/register.py

I had a bug where workflow registration would fail while creating a log directory and log file because linux (or at least Ubuntu) doesn't allow colons in file names. This change fixes that by replacing the colons in the log path with underscores. I've attached the error logs and a screenshot of the error. 
[.latch_report.tar.gz](https://github.com/latchbio/latch/files/9847043/default.latch_report.tar.gz)

Fixed mkdir invalid argument error when registering workflow

---

CHANGELOG.md
setup.py

gets rid of annoying warning on any subcommand that makes a request:
```
/root/miniconda/envs/jupyterlab/lib/python3.9/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```
- https://github.com/psf/requests/releases/tag/v2.28.1
- https://github.com/psf/requests/issues/6177

use a version of `requests` that supports the version of `chardset` it installs

---

CHANGELOG.md
latch_cli/centromere/utils.py
setup.py

Fixes case when library code uses a fake import as a subclass, eg in torch:
```
--Traceback (most recent call last)--
/Users/nsofroniew/opt/anaconda3/envs/latch/lib/python3.9/site-packages/torch/jit/_monkeytype_config.py:73 in <module>
71| if _IS_MONKEYTYPE_INSTALLED:
72|
> 73|     class JitTypeTraceStoreLogger(CallTraceStoreLogger):
74|         """A JitTypeCallTraceLogger that stores logged traces in a CallTraceStore."""
75|         def __init__(self, store: CallTraceStore):
76|             super().__init__(store)
77|
```

allow imports that subclass from nested imports

---

latch_cli/config/user.py

Using `self._token_path.touch(exist_ok=True)` throws a `PermissionError` when the token file only has readonly permissions.
```python 
Unable to display contents of () - printing traceback:
/opt/miniconda/envs/jupyterlab/bin/latch:8 in <module>
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/click/core.py:1130 in __call__
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/click/core.py:1055 in main
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/click/core.py:1657 in invoke
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/click/core.py:1404 in invoke
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/click/core.py:760 in invoke
/opt/miniconda/envs/jupyterlab/lib/python3.9/site-packages/latch_cli/main.py:246 in ls …
```

fix: readonly permission errors

---

CHANGELOG.md
latch_cli/constants.py
latch_cli/services/cp.py

s3 enforces a limit of 10k parts, which causes large multipart uploads to fail because our chunk size is too small

fix: large file upload error

---

docs/source/basics/defining_environment.md
latch_cli/docker_utils/__init__.py

`conda init` prefixes `PATH` with `/opt/conda/bin:/opt/conda/condabin`. We want the first directory in path to be the environment defined in the environment.yaml file instead

No `conda init` 

---

latch_cli/docker_utils/__init__.py
latch_cli/snakemake/serialize.py
latch_cli/snakemake/single_task_snakemake.py
latch_cli/snakemake/workflow.py

* `temp`
* `report`
Serialize sufficient fields to reconstruct tuples when parsing for each
task. The following an example for `report`.
```
@workflow.output(
report (
"results/qc/multiqc.html" ,
caption = "../report/multiqc.rst" ,
category = "Quality control" ,
) ,
)
```

More snakemake fixes

---

latch_cli/snakemake/workflow.py

motivation is that certain Snakefiles use logs from previous jobs as inputs to subsequent jobs

sm make log files also outputs

---

latch/resources/tasks.py
latch_cli/services/register/register.py
latch_cli/snakemake/config/parser.py
latch_cli/snakemake/serialize.py
latch_cli/snakemake/workflow.py
latch_cli/utils/__init__.py

This shaves ~10 seconds from JIT.
Purpose of docker build in the JIT step was to add the latch-entrypoint file to the container of each job task.
We remove this and each job task now fetches the entrypoint before executing pyflyte code.
```
Command:
/bin/bash
-c
exec 3>&1 4>&2 && latch cp latch:///.snakemake_latch/workflows/snakemake_test_init/entrypoint.py /opt/latch/latch_entrypoint.py && ( pyflyte-execute --inputs s3://prion-flyte-prod/metadata/propeller/1-development-fd1bf39e849e44f98874/n4/data/inputs.pb --output-prefix s3://prion-flyte-prod/metadata/propeller/1-development-fd1bf39e849e44f98874/n4/data/0 --raw-output-data-prefix s3://prion-flyte-prod/q9/fd1bf39e849e44f98874-n4-0 --checkpoint-path s3://prion-flyte-prod/q9/fd1bf39e849e44f98874-n4-0/_flytecheckpoints --prev-checkpoint …
```

Remove docker build from snakemake JIT 

---

latch_cli/snakemake/config/parser.py
latch_cli/snakemake/serialize.py
latch_cli/snakemake/serialize_utils.py

Because parameter types in the jit workflow are now imported from the latch_metadata package they all use fully qualified names. If developer constructs their own types in that package we will have to figure out how to bring appropriate import statement to jit code in the future

add import + better message for par

---

latch_cli/snakemake/serialize.py
latch_cli/snakemake/serialize_utils.py
latch_cli/snakemake/workflow.py

- intermediate outputs from snakemake tasks are now uploaded to latch
- bug fix where `/root` paths caused an iteration over the entire root directory

more snakemake bug fixes

---

latch_cli/main.py
latch_cli/services/register/register.py
latch_cli/snakemake/serialize.py
latch_cli/snakemake/workflow.py

way simpler than i thought, just very opaque
idea is to make every task upload its outputs to latch instead of s3, as caching is broken for s3 outputs because they don't have hashes

snakemake caching 

---

latch_cli/snakemake/workflow.py

In a Snakefile, it is possible for two different input files to have the same parameter name as long as they are defined in different rules. This can lead to name collisions because we use a global mapping (across all rules) of param_name -> input_file.
To avoid this name collision, I add a check and raise an error if it doesn't pass. 
I considered adding the job_id to the front of all the variable names, but I suspect that this will make the entrypoint file even less readable. Since this seems like enough of an edge case, I would prefer to just fail and raise an error rather than append the job id to all the variable names.

fix: prevent name collisions on input parameters

---

latch_cli/docker_utils/__init__.py

Removing copy for .latch/* into /root in the Dockerfile generation. 
We are already explicitly copying the `snakemake_jit_entrypoint` file explicitly, so I don't think this is necessary. 
Also, I think we should make all copies from .latch explicit because we can potentially override user data which can be confusing for developer. For example, I was running into an issue where the .latch/config file was overriding the user's config directory which caused the JIT task to fail.

remove .latch dir copy from dockerfile generation

---

latch_cli/snakemake/workflow.py

This will fail without this fix (input for a target job has keyword param):
```
rule all:
input:
file = "file1.txt"
touch:
output:
file = "file1.txt"
shell:
"touch {output.file}" 
```

fix: use variable_name_for_value instead of variable_name_for_file

---

CHANGELOG.md
docs/source/snakemake/quickstart.md
latch_cli/snakemake/single_task_snakemake.py
setup.py

block_content overrides must return a generator, not None. Otherwise, the workflow will error out.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/snakemake/__init__.py", line 654, in snakemake
workflow.include(
File "/usr/local/lib/python3.9/site-packages/snakemake/workflow.py", line 1213, in include
code, linemap, rulecount = parse(
File "/usr/local/lib/python3.9/site-packages/snakemake/parser.py", line 1274, in parse
for t, orig_token in automaton.consume():
File "/usr/local/lib/python3.9/site-packages/snakemake/parser.py", line 100, in consume
for t, orig in self.state(token):
File "/usr/local/lib/python3.9/site-packages/snakemake/parser.py", line 1226, in python
for t in self.subautomaton(token.string).consume():
File …
```

fix ruleorder directive 

---

latch/resources/workflow.py
latch_cli/snakemake/config/parser.py
latch_cli/snakemake/serialize_utils.py
latch_cli/utils/__init__.py

We should be able to generate best-effort metadata from input parameters when no metadata is provided. 
This makes it easier for user to go from script -> workflow with minimal overhead

Generate metadata from input parameters

---

src/latch/registry/table.py
uv.lock

fix upserting enum columns in registry api

---

pyproject.toml

Third time's the charm. 😅 
The `py.typed` files were missing from the built distribution because the `pyproject.toml` was configured to include only `.py` source files. I've updated the configuration to also include `py.typed`, so these files will now be part of the distribution and available in pypi installs.
Thank you for the patience and thanks for including this!
- Updated `pyproject.toml` so `py.typed` files in the `src/` package directories are included in the built distribution.
I confirmed that the tarball built with `uv build` includes the `py.typed` files after this change to the `pyproject.toml`, and that no other files are added or removed.
```console
$ tar -t -f dist/latch-2.61.1.tar.gz | grep py.typed
latch-2.61.1/src/latch/py.typed
latch-2.61.1/src/latch_cli/py.typed …
```

chore: Package py.typed files with the built distribution
